data_path: /mnt/c/Users/Lennart/Desktop/Studium/MLUnfoldingForBellTests/data/truth_finalstate.csv

input_shape: 10
num_dense_layers: 8
dense_nodes: 768
activation_functions: relu
output_activation: linear
batch_normalization: True
dropout_rate: 0.2
l2_regularization: 0.003

learning_rate: 0.0007
batch_size: 256
epochs: 500
early_stopping_patience: 20