data_path: data/hww_1M_MG5_final
raw_data_path: data/hww_1M_MG5
processed_features_path: data/hww_1M_MG5_final_X
processed_targets_path: data/hww_1M_MG5_final_y
detector_sim_path: data/hww_1M_MG5_final_detector_sim
truth_path: data/hww_1M_MG5_final_truth

input_shape: 10
num_dense_layers: 8
dense_nodes: 1000
activation_functions: elu
output_activation: linear
batch_normalization: True
dropout_rate: 0.1
l2_regularization: 0.0067008
learning_rate: 0.0026858
batch_size: 128
epochs: 500
patience: 5